#!/bin/bash

# Save the number of your cores to the variable CPUCORES
CPUCORES=$(nproc)
# You can change this variable to compile in any other folder
CPATH="$HOME/Downloads"
# to include the .config in the deb-files we use this patch
BUILDDEB_FILE="scripts/package/builddeb"
MARKER="# Include .config in headers package (for DKMS and module signing)"
# PATCH="add_config_to_headers.patch"

# Color functions for text colors
RED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
BWHITE='\033[1;37m'
ITAL='\033[3;37m\033[1;37m'
ITALYELL='\033[3;37m\033[1;37m\033[3;33m'
FLSH='\033[1;5m'
FLSHGREEN='\033[0;32m\033[1;5m'
NC='\033[0m' # No Color

function red {
    printf "${RED}$@${NC}\n"
}

function green {
    printf "${GREEN}$@${NC}\n"
}

function yellow {
    printf "${YELLOW}$@${NC}\n"
}

function blue {
    printf "${BLUE}$@${NC}\n"
}

function bwhite {
    printf "${BWHITE}$@${NC}\n"
}

function ital {
    printf "${ITAL}$@${NC}\n"

}

function italyell {
    printf "${ITALYELL}$@${NC}\n"
}

function flsh {
    printf "${FLSH}$@${NC}\n"
}

function flshgreen {
    printf "${FLSHGREEN}$@${NC}\n"
}

echo 'We need sudo for some commands like dependencies, dkms, to copy the .config file after build time and for dpkg'
echo ' to install the deb files afterwards. sudo will be requested only one time here:'
sudo -v # requesting sudo permissions
while true; do
  sudo -v
  sleep 60
done & # keep sudo active until wait quits the script
echo ''
echo ''
echo  $(green 'Kernel Pull Merge Script v1.1 for Minisforum UM790Pro')
echo ''
echo $(yellow 'Silently installing dependencies..')
sudo apt-get install -y git dwarves build-essential fakeroot bc kmod cpio libxi-dev libncurses5-dev libgtk2.0-dev libglib2.0-dev libglade2-dev libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev dpkg-dev autoconf libdw-dev cmake zstd packagekit qt5ct libpackagekitqt5-dev nano patch patchutils > /dev/null
cd $CPATH
rm linux-*.tar.xz 2> /dev/null
#if the external modules have been installed we remove it here..
sudo dkms remove -m anbox-ashmem/1 --all 2> /dev/null
sudo dkms remove -m anbox-binder/1 --all 2> /dev/null
rm -R -f ''$CPATH'/kernel' 2> /dev/null
mkdir kernel # We create a work directory folder
# clear
echo ''
echo ''
echo $(ital 'make sure this folder does not contain any kernel files before proceeding')
echo $(ital 'as tar will otherwise fail to correctly unpack files to the')
echo $(ital 'work directory we just created:')
echo ''
echo $(red ''$CPATH'')
echo ''
read -p " $(italyell 'Which kernel version do you want to compile?') example: $(italyell '6.10.8') -->> " KERNEL_VERSION
echo ''
echo $(ital 'kernel version you selected to compile from source: '$KERNEL_VERSION'')
echo ''
echo ''
echo $(italyell 'Downloading source code for kernel version: '$KERNEL_VERSION' from: https://kernel.org')
echo ''
wget 'https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-'$KERNEL_VERSION'.tar.xz'
echo $(green 'DONE!')
echo ''
echo ''
echo $(italyell 'unpacking the source code tar.xz file from: https://kernel.org to the kernel source build work directory:')
echo $(ital ''$CPATH'/kernel')
tar xvf linux-* -C kernel/ --strip-components=1 > /dev/null # unpacking the tar.xz to the kernel folder
cd kernel # we open the kernel folder
echo ''
cp /boot/config-$(uname -r) ./.config # we copy your current configuration file from /boot/config to the kernel folder and rename it to .config
echo $(green 'DONE!')
echo ''
echo ''
echo $(italyell 'Writing defaults to fresh .config options:')
echo ''
make olddefconfig # we re-generate the copied config file to update new lines in newer kernel versions with the pre-defined default answer
echo $(green 'DONE!') $(italyell 'Make build configuration file with standard defaults options for kernel version: '$KERNEL_VERSION' has been created..')
echo ''
echo ''
# echo $(blue 'Downloading patch file for adding .config-file to deb creation: '$PATCH'')
# echo ''
# wget 'https://raw.githubusercontent.com/SoulInfernoDE/compile-kernel-from-source/refs/heads/v6.x/nogui/add_config_to_headers.patch'
# echo ''
# echo ''
echo $(blue 'Downloading the merge fragments file: .config-fragment - if you need some lines changed or added please create a pull request')
echo ''
wget 'https://raw.githubusercontent.com/SoulInfernoDE/compile-kernel-from-source/um790pro/nogui/.config-fragment'
echo $(green 'DONE!')
echo ''
echo ''
echo $(blue ''$CPATH'/kernel/.config-fragment') '<<----'
echo ''
cat './.config-fragment'
echo ''
echo ''
# Using terminal script from torvalds to modify the needed lines into the .config file found in the kernel sources under kernel/scripts/kconfig/merge_config.sh
echo $(italyell 'Merge config file  .config-fragment into the main '$CPATH'/kernel/.config file')
$CPATH/kernel/scripts/kconfig/./merge_config.sh .config .config-fragment
echo $(green 'DONE!')
# echo 'merging necessary options into the .config file:'
echo ''
echo ''
echo $(italyell 'Resorting '$CPATH'/kernel/.config file')
make olddefconfig # we have updated lines at the end of the config file, however we re-generate the config file again to maintain the correct structure for the build process to success
echo $(green 'DONE!')
echo ''
echo ''
# apply patch, if not already done
if grep -qF "$MARKER" "$BUILDDEB_FILE"; then
    echo "Patch already applied – skipping ..."
else
    echo "Applying patch ..."
    sed -i "/^install_kernel_headers () {/,/^}/ {
      /^}/ i\
        \ \ \ \ $MARKER\n\
        \ \ \ \ if [ -f \"\$objtree/.config\" ]; then\n\
        \ \ \ \ \ \ echo \"Including .config in headers package\"\n\
        \ \ \ \ \ \ cp \"\$objtree/.config\" \"\$pdir/usr/src/linux-headers-\${version}/.config\"\n\
        \ \ \ \ fi
    }" "$BUILDDEB_FILE"
    echo "Patch successfull applied. The .config file will now be copied while deb install is running. Thus module signing is enabled."
fi
cp .config config > /dev/null # enables one time internal module signing addition at build time
echo ''
echo ''
echo $(yellow 'You have a maximum of '$CPUCORES' cpu cores for building from source')
echo ''
read -r -p "
###############################################################
#               $(flshgreen 'Ready to start compiling!')                     #
# $(ital 'To manually compile enter: time nice make bindeb-pkg -j'$CPUCORES'')   #
#                                                             #
# $(flshgreen 'deb-file creation will start.') $(green 'Do you want to continue?')      #
#                                                             #
#   $(ital '- Make sure configuration changes are correct! -')          #
############################################################### 
(y|Y)es (n|N)o # " input

case $input in
    [yY][eE][sS]|[yY])
 echo "Executing..!"
 ;;
    [nN][oO]|[nN])
 echo "No, we stop here.."
 exit 1
       ;;
    *)
 echo "Invalid selection input.. ..aborting!"
 exit 1
 ;;
esac

echo $(italyell 'Sit back! This can take a very long time depending on your cpu power!')
echo ''
time nice make bindeb-pkg -j$CPUCORES # we start compiling process with: counting the time needed to compile, show less and nicer compile information, generate deb-files at the end and use x-cpu cores to speed up compiling procedure

read -r -p "
###############################################################
# $(flshgreen 'deb-files will be installed.') $(green 'Do you want to continue?')       #
#                                                             #
#   $(ital '- Make sure compiling finished successfully!')              #
#   $(ital '- Manual installation: sudo dpkg -i '$CPATH'/linux-*.deb')       #
############################################################### 
(y|Y)es (n|N)o # " install

case $install in
    [yY][eE][sS]|[yY])
 echo "Executing..!"
 ;;
    [nN][oO]|[nN])
 echo "No, we stop here.."
 exit 1
       ;;
    *)
 echo "Invalid selection input.. ..aborting!"
 exit 1
 ;;
esac

ls $CPATH/linux-*.deb
echo $(italyell 'will now be installed!')
echo ''
echo ''
# saving the kernelversion text to KVER
KVER=$(make -s kernelrelease)
echo ''
# sudo cp "$CPATH/kernel/.config" /usr/src/linux-headers-"$KERNEL_VERSION"*/
# echo '.config-file has been copied to the kernel headers folder as this is needed for module signing!' # if .deb files are installed without this then modules will not be signed
echo ''
echo ''
sudo dpkg -i $CPATH/linux-*.deb # we install the compiled *.deb kernel files
echo $(green 'DONE!')
echo ''
echo $(green 'If the script has an error for you, please report it on github. You can leave a screenshot if you like to in the issues section')
echo ''
echo $(red 'If you are using uefi hardware with secure boot you MUST sign your kernel with a generated signature to be able to boot the new kernel!')
echo $(red 'You can use https://raw.githubusercontent.com/SoulInfernoDE/compile-kernel-from-source/um790pro/signkernel/signukuu for this if you wish!')
echo ''
echo ''
wait
